# Generated by Django 4.1.7 on 2024-05-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='stock',
            field=models.CharField(max_length=10),
        ),
    ]
